site:
  title: Rampage Documentation
  start_page: rampage::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: src/docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site
